language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base libgl1-mesa-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - make -j$(nproc)
  - wget -c "https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage"
  - bash -ex pkg2appimage ptouch-770.yml

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/ptouch*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
